export const SERVICE_CATEGORIES = [
  { id: '1', name: 'EV Charging Help', icon: '⚡', color: '#2563EB', price: 25, duration: '30-60 min', badge: 'Available Now', badgeColor: '#16A34A' },
  { id: '2', name: 'Home Assistance', icon: '🏠', color: '#16A34A', price: 35, duration: '1-2 hrs', badge: 'Available Now', badgeColor: '#16A34A' },
  { id: '3', name: 'Cleaning Help', icon: '🧹', color: '#F97316', price: 40, duration: '2-3 hrs', badge: 'High Demand', badgeColor: '#F97316' },
  { id: '4', name: 'Pickup & Drop', icon: '📦', color: '#2563EB', price: 15, duration: '30-45 min', badge: 'Available Now', badgeColor: '#16A34A' },
  { id: '5', name: 'Senior Assistance', icon: '👴', color: '#16A34A', price: 30, duration: '1-3 hrs', badge: 'Scheduled Only', badgeColor: '#2563EB' },
  { id: '6', name: 'Technician Visit', icon: '🔧', color: '#2563EB', price: 45, duration: '1-2 hrs', badge: 'Available Now', badgeColor: '#16A34A' },
  { id: '7', name: 'Delivery Assistance', icon: '🚚', color: '#F97316', price: 20, duration: '30-60 min', badge: 'Available Now', badgeColor: '#16A34A' },
  { id: '8', name: 'Moving Help', icon: '🏗️', color: '#2563EB', price: 60, duration: '2-4 hrs', badge: 'Scheduled Only', badgeColor: '#2563EB' },
  { id: '9', name: 'Errand Support', icon: '🏃', color: '#16A34A', price: 18, duration: '30-60 min', badge: 'Available Now', badgeColor: '#16A34A' },
  { id: '10', name: 'Emergency Help', icon: '🚨', color: '#DC2626', price: 50, duration: '15-30 min', badge: 'High Demand', badgeColor: '#F97316' },
];

export const SERVICE_DETAILS = {
  '1': {
    name: 'EV Charging Help',
    description: 'Book a verified Buddy to assist with EV charging support at your selected location.',
    includes: ['Buddy visit to selected location', 'Assistance in locating/using charging point', 'Charging support as per service availability', 'Basic issue reporting'],
    excludes: ['Vehicle repair', 'Battery replacement', 'Towing unless separately selected', 'Paid charging cost by station'],
    cancellation: 'Free cancellation up to 30 minutes before scheduled time.',
    fields: [
      { key: 'vehicleMake', label: 'Vehicle Make', type: 'text', required: true },
      { key: 'vehicleModel', label: 'Vehicle Model', type: 'text', required: true },
      { key: 'vehicleNumber', label: 'Vehicle Number', type: 'text', required: false },
      { key: 'batteryPercentage', label: 'Current Battery %', type: 'number', required: true },
      { key: 'issueType', label: 'Charging Issue Type', type: 'select', required: true, options: ['Need nearby charging assistance', 'Unable to use charger', 'Need help reaching charging station', 'Charging cable issue', 'App/payment issue at station', 'Other'] },
      { key: 'photos', label: 'Photos (optional)', type: 'image', required: false },
    ],
  },
  '2': {
    name: 'Home Assistance',
    description: 'Get help with household tasks from a verified Buddy.',
    includes: ['General home help', 'Light maintenance', 'Organization assistance'],
    excludes: ['Heavy construction', 'Electrical wiring', 'Plumbing repairs'],
    cancellation: 'Free cancellation up to 1 hour before.',
    fields: [
      { key: 'taskType', label: 'Task Type', type: 'select', required: true, options: ['Furniture assembly', 'Wall mounting', 'Organization', 'Light repairs', 'Other'] },
      { key: 'description', label: 'Task Description', type: 'textarea', required: true },
      { key: 'photos', label: 'Photos (optional)', type: 'image', required: false },
    ],
  },
  '3': {
    name: 'Cleaning Help',
    description: 'Professional cleaning service at your doorstep.',
    includes: ['Deep cleaning', 'Surface cleaning', 'Bathroom/kitchen cleaning'],
    excludes: ['Pest control', 'Carpet shampooing', 'External window cleaning'],
    cancellation: 'Free cancellation up to 2 hours before.',
    fields: [
      { key: 'propertyType', label: 'Property Type', type: 'select', required: true, options: ['Apartment', 'House', 'Office', 'Studio'] },
      { key: 'rooms', label: 'Number of Rooms', type: 'number', required: true },
      { key: 'cleaningType', label: 'Cleaning Type', type: 'select', required: true, options: ['Regular', 'Deep Clean', 'Move-in/Move-out', 'Post-construction'] },
      { key: 'supplies', label: 'Need Cleaning Supplies?', type: 'select', required: true, options: ['Yes', 'No'] },
      { key: 'instructions', label: 'Special Instructions', type: 'textarea', required: false },
    ],
  },
  '4': {
    name: 'Pickup & Drop',
    description: 'Get items picked up and delivered safely.',
    includes: ['Item pickup', 'Safe transport', 'Delivery confirmation'],
    excludes: ['Fragile/high-value items without insurance', 'Illegal items'],
    cancellation: 'Free cancellation up to 30 minutes before.',
    fields: [
      { key: 'itemType', label: 'Item Type', type: 'text', required: true },
      { key: 'itemSize', label: 'Item Size', type: 'select', required: true, options: ['Small', 'Medium', 'Large'] },
      { key: 'recipientName', label: 'Recipient Name', type: 'text', required: true },
      { key: 'recipientPhone', label: 'Recipient Phone', type: 'phone', required: true },
      { key: 'instructions', label: 'Delivery Instructions', type: 'textarea', required: false },
    ],
  },
  '5': {
    name: 'Senior Assistance',
    description: 'Compassionate assistance for elderly family members.',
    includes: ['Companionship', 'Errand help', 'Mobility assistance', 'Appointment accompaniment'],
    excludes: ['Medical procedures', 'Medication administration', 'Overnight care'],
    cancellation: 'Free cancellation up to 2 hours before.',
    fields: [
      { key: 'assistanceType', label: 'Assistance Type', type: 'select', required: true, options: ['Companionship', 'Errand help', 'Appointment', 'Mobility', 'Other'] },
      { key: 'personName', label: 'Person Name', type: 'text', required: true },
      { key: 'ageGroup', label: 'Age Group', type: 'select', required: true, options: ['60-70', '70-80', '80+'] },
      { key: 'emergencyContact', label: 'Emergency Contact', type: 'phone', required: true },
      { key: 'instructions', label: 'Instructions', type: 'textarea', required: false },
    ],
  },
  '6': {
    name: 'Technician Visit',
    description: 'Expert technician for device and appliance issues.',
    includes: ['Diagnosis', 'Basic repair', 'Installation support'],
    excludes: ['Spare parts cost', 'Warranty claims processing'],
    cancellation: 'Free cancellation up to 1 hour before.',
    fields: [
      { key: 'deviceType', label: 'Device/Appliance Type', type: 'text', required: true },
      { key: 'issueDescription', label: 'Issue Description', type: 'textarea', required: true },
      { key: 'brand', label: 'Brand/Model', type: 'text', required: false },
      { key: 'warranty', label: 'Warranty Status', type: 'select', required: false, options: ['Under warranty', 'Expired', 'Not sure'] },
      { key: 'photos', label: 'Photos/Video', type: 'image', required: false },
    ],
  },
  '7': {
    name: 'Delivery Assistance',
    description: 'Quick and reliable delivery support.',
    includes: ['Package pickup', 'Safe delivery', 'Delivery proof'],
    excludes: ['Hazardous materials', 'Oversized items'],
    cancellation: 'Free cancellation up to 15 minutes before.',
    fields: [
      { key: 'packageType', label: 'Package Type', type: 'text', required: true },
      { key: 'recipientName', label: 'Recipient Name', type: 'text', required: true },
      { key: 'recipientPhone', label: 'Recipient Phone', type: 'phone', required: true },
      { key: 'proofRequired', label: 'Delivery Proof Required?', type: 'select', required: true, options: ['Photo', 'Signature', 'OTP', 'None'] },
    ],
  },
  '8': {
    name: 'Moving Help',
    description: 'Help with moving items between locations.',
    includes: ['Loading/unloading', 'Careful handling', 'Basic packing'],
    excludes: ['Long-distance transport', 'Storage', 'Insurance'],
    cancellation: 'Free cancellation up to 4 hours before.',
    fields: [
      { key: 'itemList', label: 'Item List', type: 'textarea', required: true },
      { key: 'floorFrom', label: 'Floor (From)', type: 'number', required: true },
      { key: 'floorTo', label: 'Floor (To)', type: 'number', required: true },
      { key: 'elevator', label: 'Elevator Available?', type: 'select', required: true, options: ['Yes', 'No'] },
      { key: 'photos', label: 'Photos', type: 'image', required: false },
    ],
  },
  '9': {
    name: 'Errand Support',
    description: 'Get help running errands around town.',
    includes: ['Shopping', 'Bill payments', 'Document pickup', 'Queue waiting'],
    excludes: ['Illegal activities', 'Financial transactions'],
    cancellation: 'Free cancellation up to 30 minutes before.',
    fields: [
      { key: 'taskDescription', label: 'Task Description', type: 'textarea', required: true },
      { key: 'pickupLocation', label: 'Pickup Location', type: 'text', required: false },
      { key: 'paymentInstructions', label: 'Payment Instructions', type: 'textarea', required: false },
    ],
  },
  '10': {
    name: 'Emergency Help',
    description: 'Urgent assistance when you need it most.',
    includes: ['Immediate response', 'Priority assignment', 'Emergency coordination'],
    excludes: ['Medical emergencies (call 911)', 'Fire emergencies'],
    cancellation: 'Non-refundable once Buddy is assigned.',
    fields: [
      { key: 'emergencyType', label: 'Emergency Type', type: 'select', required: true, options: ['Lockout', 'Flat tire', 'Stranded', 'Other'] },
      { key: 'description', label: 'Description', type: 'textarea', required: true },
      { key: 'photos', label: 'Photos', type: 'image', required: false },
    ],
  },
};
